ALTER TABLE BlogComments
DROP CONSTRAINT FK__BlogComme__BlogI__534D60F1;

ALTER TABLE BlogComments
ADD CONSTRAINT FK_BlogComments_BlogID
FOREIGN KEY (BlogID)
REFERENCES Blogs(ID)
ON UPDATE CASCADE
ON DELETE CASCADE;
